# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayuda.ui'
#
# Created: Fri May 30 17:11:46 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlg_AyudaDocLux(object):
    def setupUi(self, dlg_AyudaDocLux):
        dlg_AyudaDocLux.setObjectName(_fromUtf8("dlg_AyudaDocLux"))
        dlg_AyudaDocLux.resize(869, 511)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ayuda/recursos/imagenes/ayuda_rcs/icon_doclux.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_AyudaDocLux.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(dlg_AyudaDocLux)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_Ayuda = QtGui.QTabWidget(dlg_AyudaDocLux)
        self.tabWidget_Ayuda.setObjectName(_fromUtf8("tabWidget_Ayuda"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setEnabled(True)
        self.textEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_4.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textEdit_3 = QtGui.QTextEdit(self.tab_3)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.gridLayout_5.addWidget(self.textEdit_3, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textEdit_4 = QtGui.QTextEdit(self.tab_4)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.gridLayout_6.addWidget(self.textEdit_4, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.textEdit_5 = QtGui.QTextEdit(self.tab_5)
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.gridLayout_7.addWidget(self.textEdit_5, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.textEdit_7 = QtGui.QTextEdit(self.tab_6)
        self.textEdit_7.setObjectName(_fromUtf8("textEdit_7"))
        self.gridLayout_8.addWidget(self.textEdit_7, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.textEdit_6 = QtGui.QTextEdit(self.tab_7)
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.gridLayout_9.addWidget(self.textEdit_6, 0, 0, 1, 1)
        self.tabWidget_Ayuda.addTab(self.tab_7, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_Ayuda)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(dlg_AyudaDocLux)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(dlg_AyudaDocLux)
        self.tabWidget_Ayuda.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dlg_AyudaDocLux.close)
        QtCore.QMetaObject.connectSlotsByName(dlg_AyudaDocLux)

    def retranslateUi(self, dlg_AyudaDocLux):
        dlg_AyudaDocLux.setWindowTitle(QtGui.QApplication.translate("dlg_AyudaDocLux", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:16pt; font-weight:600; font-style:italic;\">DocLux. Aplicación para el tratamiento de imágenes de archivos por lotes.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">A continuación se describen las generalidades del ambiente de DocLux:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:200; font-style:italic; color:#000000;\">     </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/01_visor_inicio.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; color:#000000;\">La aplicación para tratar imágenes de archivos históricos por lotes de está dividida en 7 áreas fundamentales. Cada una de ellas se muestran a continuación.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Barra de menú</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">: </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:200; font-style:italic; color:#000000;\">  </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/02_barra_de_menu.png\" /><span style=\" font-family:\'Sans\'; font-size:10pt;\"><br /></span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Barra de herramientas:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/03_bh_plugins.png\" /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Área de trabajo:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/04_visor_area_de_trabajo.png\" /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Imágenes </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">cargadas:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/05_visor_imagenes_cargadas.png\" /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Lista de comandos:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/06_visor_lista_de_comandos.png\" /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; font-weight:200; font-style:italic; color:#000000;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Barra de herramientas inferior:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/07_bh_inferior.png\" /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; color:#000000;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab), QtGui.QApplication.translate("dlg_AyudaDocLux", "Ayuda DocLux", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_2.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">  </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">BARRA DE MENÚ</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/02_barra_de_menu.png\" /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">La Barra de menú contiene cada una de las opciones que posibilita la aplicación DocLux.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">. Archivo.</span><span style=\" font-family:\'Sans\'; font-size:12pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Este menú permite cargar </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Nuevas</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> imágenes al sistema, así como </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Adicionar</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> otras imágenes a la lista existente. Además, permite </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Guardar</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> y </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Exportar</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> la(s) imágenes y posibilita </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Minimizar</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> y </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">Salir</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> de la aplicación.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/08_menu_archivo.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">A continuación se explican cada una de las opciones del menú.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.1. Nuevas. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_nuevas_imgs.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta opción permite cargar nuevas imágenes para ser procesadas.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.2. Adicionar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_adicionar_imgs.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite </span><span style=\" font-family:\'Sans\'; font-size:10pt;\">adicionar más imágenes a la lista existente.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.3. Abrir proyecto. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_open_project_dlx.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción permite </span><span style=\" font-family:\'Sans\'; font-size:10pt;\">abrir un proyecto de DocLux con formato </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">.dlx</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> guardado en un directorio.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.4. Guardar actual. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción permite guardar la imagen actual en diferentes formatos (*.jpg; *.jpeg; *.png; *.tiff).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.5. Guardar todas. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_all_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción permite guardar todas las imágenes cargadas en diferentes formatos (*.jpg; *.jpeg; *.png; *.tiff).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.6. Exportar actual. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_one_pdf.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción permite exportar la imagen actual en formato *.pdf</span><span style=\" font-family:\'Sans\'; font-size:10pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.7. Exportar todas. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_all_pdf.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción permite exportar todas las imágenes cargadas/procesadas en formato *.pdf</span><span style=\" font-family:\'Sans\'; font-size:10pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.8. Guardar proyecto. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_project.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite </span><span style=\" font-family:\'Sans\'; font-size:10pt;\">guardar un proyecto de DocLux con formato </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">.dlx</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> guardado en un directorio.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.9. Minimizar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_minimizar.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción permite minimizar la aplicación.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.10. Salir.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_exit.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta opción permite cerrar/salir la aplicación.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section2\"></a><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">2</span><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">. Editar.</span><span style=\" font-family:\'Sans\'; font-size:12pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Este menú permite </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Deshacer</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> y </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Rehacer</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> la(s) acciones realizadas a la imagen actual que se muestra en el área de trabajo. Además, permite </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Eliminar</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\"> la imagen actual mostrada/seleccionada en el área de trabajo.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/09_menu_editar.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">A continuación se explican cada una de las opciones.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">2.1. Deshacer. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_deshacer.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite volver al estado anterior en que se encontraba la imagen antes de aplicarle determinado filtro o transformación.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">2.2. Rehacer. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_rehacer.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite devolver al estado que había adquirido la imagen anteriormente.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">2.3. Eliminar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_delete_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite eliminar la imagen actual mostrada/seleccionada.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section3\"></a><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">3</span><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">. Herramientas.</span><span style=\" font-family:\'Sans\'; font-size:12pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Este menú permite </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Limpiar </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">área de intercambio</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">que permite gestionar el directorio donde se desea guardar el archivo raíz de DocLux.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">A continuación se explican cada una de las opciones.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">3.1. Limpiar </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">área de intercambio</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/010_menu_herramientas.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción muestra una lista con cada una de las modificaciones que ha sufrido la imagen actual que se muestra en el área de Imagen Procesada.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"></a><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">. Plugins.</span><span style=\" font-family:\'Sans\'; font-size:12pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Este menú contiene cada uno de los plugins/filtros que brinda el sistema, que se aplican a la(s) imágene(s) que se carguan para ser procesadas. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/011_menu_plugins.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">A continuación se explican cada una de las opciones.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section3\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.1. Balancear colores. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_balancear_color.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede balancear los colores de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.2. Brillo.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_brillo.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede modificar el brillo de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section5\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.3. Contraste.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_contraste.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede modificar el contraste de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.4. Escala de grises.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_grises.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción convierte a escala de grises (blanco y negro) la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.5. Escalar +. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_zoom-in.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta herramienta permite aumentar el tamaño de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Permite acercar la imagen.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4.6. Escalar -.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_zoom-out.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta herramienta permite disminuir el tamaño de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Permite alejar la imagen.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4.7. Invertir imagen.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_rotate_hrzt_vert.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta herramienta puede invertir la imagen actual mostrada/seleccionada, de derecha a izquierda o de arriba a abajo.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4.8. Limpiar imagen OpenCV.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_clean_bg_01.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta realiza la limpieza de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, utilizando algoritmos de limpieza de imágenes de bibliotecas OpenCV (Python bindings for the computer vision library).</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4.9. Limpiar imagen PIL.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_clean_bg_02.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta realiza la limpieza de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, utilizando algoritmos de limpieza de imágenes de bibliotecas PIL (Python Imaging Library).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4.10. Limpiar imagen SciPy.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_clean_bg_03.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta realiza la limpieza de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, utilizando algoritmos de limpieza de imágenes de bibliotecas SciPy (Scientific tools for Python).</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.11. Modificar colores.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_modificar_color.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede modificar los colores RGB (rojo, verde y azul) de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section2\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.12. Rotar a la derecha.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_rotate-right.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta permite rotar la imagen 90</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; vertical-align:super;\">0 </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">a la derecha, es decir, en el sentido de las manecillas del reloj.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section3\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.13. Rotar a la izquierda.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_rotate-left.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta permite rotar la imagen 90</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; vertical-align:super;\">0 </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">a la izquierda, es decir, en sentido contrario de las manecillas del reloj.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section5\"></a><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">5</span><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600;\">. Ayuda.</span><span style=\" font-family:\'Sans\'; font-size:12pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Este menú contiene la opción </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Acerca de</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> que brinda información relevante acerca de la aplicación DocLux. También ofrece la opción de </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Ayuda </span><span style=\" font-family:\'Sans\'; font-size:10pt;\">que permite acceder a la ayuda de DocLux, donde se explica como trabajar e interactuar con la herramienta.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/012_menu_ayuda.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">A continuación se explican cada una de las opciones.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section2\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">5</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.1. Acerca de.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_acerca_de.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Esta opción muestra datos importante acerca del sistema DocLux, del equipo de desarrollo y la licencia bajo la cual se comercializa dicho sistema</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">5.2. Ayuda.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_help.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción muestra la ayuda de DocLux; se explica el ambiente gráfico de la aplicación, así como cada una de las partes de la aplicación y cómo trabajar con ellas.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab_2), QtGui.QApplication.translate("dlg_AyudaDocLux", "Menú", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_3.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">   </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">BARRA DE HERRAMIENTAS</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/03_bh_plugins.png\" /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">La Barra de herramientas contiene cada uno de los filtros y herramientas que se le pueden aplicar a las imagenes.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.1. Nuevas. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_nuevas_imgs.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta opción permite cargar nuevas imágenes al sistema para ser procesadas.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1.2. Adicionar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_adicionar_imgs.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite </span><span style=\" font-family:\'Sans\'; font-size:10pt;\">adicionar más imágenes a la lista existente, para ser procesadas.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section3\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">3</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Balancear colores. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_balancear_color.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede balancear los colores de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Brillo.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_brillo.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede modificar el brillo de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section5\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">5</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Contraste.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_contraste.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede modificar el contraste de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">6</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Escala de grises.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_grises.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción convierte a escala de grises (blanco y negro) la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">7</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Escalar +. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_zoom-in.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta herramienta permite aumentar el tamaño de la imagen actual que se muestra en el área de Imagen Procesada. Permite acercar la imagen.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section5\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">8</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Escalar -.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_zoom-out.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta herramienta permite disminuir el tamaño de la imagen actual que se muestra en el área de Imagen Procesada. Permite alejar la imagen.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">9. Invertir imagen.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_rotate_hrzt_vert.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta herramienta puede invertir la imagen actual mostrada/seleccionada, de derecha a izquierda o de arriba a abajo.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">10. Limpiar imagen OpenCV.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_clean_bg_01.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta realiza la limpieza de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, utilizando algoritmos de limpieza de imágenes de bibliotecas OpenCV (Python bindings for the computer vision library).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">11. Limpiar imagen PIL.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_clean_bg_02.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta realiza la limpieza de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, utilizando algoritmos de limpieza de imágenes de bibliotecas PIL (Python Imaging Library).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">12. Limpiar imagen SciPy.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_clean_bg_03.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta realiza la limpieza de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, utilizando algoritmos de limpieza de imágenes de bibliotecas SciPy (Scientific tools for Python).</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">3. Modificar colores.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/plg_modificar_color.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Con esta opción puede modificar los colores RGB (rojo, verde y azul) de la imagen actual que se muestra en el área de </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">Imagen Procesada</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section2\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">4. Rotar a la derecha.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_rotate-right.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta permite rotar la imagen 90</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; vertical-align:super;\">0 </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">a la derecha, es decir, en el sentido de las manecillas del reloj.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section3\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">5. Rotar a la izquierda.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_rotate-left.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta herramienta permite rotar la imagen 90</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; vertical-align:super;\">0 </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">a la izquierda, es decir, en el sentido contrario de las manecillas del reloj.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">6. Minimizar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_minimizar.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite minimizar la aplicación.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section5\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">7. Salir.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_exit.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Esta opción permite cerrar/salir la aplicación.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab_3), QtGui.QApplication.translate("dlg_AyudaDocLux", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_4.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">ÁREA DE TRABAJO</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/04_visor_area_de_trabajo.png\" /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">La Barra de herramientas contiene cada una de las opciones que posibilita el sistema DocLux.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Área de trabajo:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">En esta área se muestra la imagen actual de las imágenes cargadas al sistema.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">2</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; color:#000000;\">Aplicar a todas: </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/chekbox_aplicar_todas.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Opción situada en la parte derecha inferior del área de trabajo, permite si está marcada que las transformaciones que sufra la imagen actual se le aplican a todas las cargadas al sistema, por el contrario de no estar marcada, los cambios sólo se aplican a la imagen actual.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab_4), QtGui.QApplication.translate("dlg_AyudaDocLux", "Área de Trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_5.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">IMÁGENES CARGADAS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/05_visor_imagenes_cargadas.png\" /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">A continuación se explica la opción.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Imágenes cargadas</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta área muestra en miniaturas cada una de las imágenes cargadas en el sistema, permitiendo seleccionar cuál de ellas se desea procesar y ser mostrada en el área de trabajo.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab_5), QtGui.QApplication.translate("dlg_AyudaDocLux", "Imágenes cargadas", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_7.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">LISTA DE COMANDOS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/06_visor_lista_de_comandos.png\" /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">A continuación se explican cada una de las opciones.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">1</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Lista de comandos</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta área muestra imágenes en miniaturas de cada una de las transformaciones que sufre la imagen actual que se muestra en el área de trabajo.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">2. Botón Aplicar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_aplicar_(lista_comando).png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Este botón permite una vez seleccionada la imagen en miniatura deseada permite actualizar la imagen que se muestra en el área de trabajo con la transformación seleccionada y elemina las restantes transformaciones en la lista de comandos.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab_6), QtGui.QApplication.translate("dlg_AyudaDocLux", "Historial de cambios", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_6.setHtml(QtGui.QApplication.translate("dlg_AyudaDocLux", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">BARRA DE HERRAMIENTAS INFERIOR</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/07_bh_inferior.png\" /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">A continuación se explican cada una de las opciones.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">1. Eliminar. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_delete_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite eliminar la imagen actual mostrada/seleccionada.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">2</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. Eliminar todas.</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_delete_all_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite eliminar todas las imágenes cargadas al sistema.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section2\"></a><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">2</span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">. </span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Deshacer. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_deshacer.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite volver al estado anterior en que se encontraba la imagen antes de aplicarle un determinado filtro.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">3. Rehacer. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_rehacer.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite devolver estado que había adquirido la imagen anteriormente.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">4. Guardar actual. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite guardar la imagen actual mostrada/seleccionada en los </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">formatos (*.jpg; *.png).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">5. Guardar todas. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_all_img.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite guardar todas las imágenes cargadas al sistema en los </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">formatos (*.jpg; *.png).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">6. Exportar actual. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_one_pdf.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite exportar la imagen actual mostrada/seleccionada, en formato *.pdf</span><span style=\" font-family:\'Sans\'; font-size:10pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">7. Exportar todas. </span><img src=\":/ayuda/recursos/imagenes/ayuda_rcs/btn_save_all_pdf.png\" /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Esta opción permite exportar todas las imágenes en formato *.pdf</span><span style=\" font-family:\'Sans\'; font-size:10pt;\">.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Ayuda.setTabText(self.tabWidget_Ayuda.indexOf(self.tab_7), QtGui.QApplication.translate("dlg_AyudaDocLux", "Barra inferior", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("dlg_AyudaDocLux", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

import recursos_rc
