# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created: Thu May  8 09:10:21 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(160, 0))
        self.widget.setMaximumSize(QtCore.QSize(160, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.thumbCargadas = QtGui.QScrollArea(self.widget)
        self.thumbCargadas.setFrameShape(QtGui.QFrame.Box)
        self.thumbCargadas.setFrameShadow(QtGui.QFrame.Plain)
        self.thumbCargadas.setLineWidth(1)
        self.thumbCargadas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thumbCargadas.setWidgetResizable(True)
        self.thumbCargadas.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.thumbCargadas.setObjectName(_fromUtf8("thumbCargadas"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 156, 194))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.miniaturas_cargadas = QtGui.QVBoxLayout()
        self.miniaturas_cargadas.setSpacing(3)
        self.miniaturas_cargadas.setObjectName(_fromUtf8("miniaturas_cargadas"))
        self.verticalLayout_2.addLayout(self.miniaturas_cargadas)
        spacerItem2 = QtGui.QSpacerItem(10, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.thumbCargadas.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.addWidget(self.thumbCargadas)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.thumbComandos = QtGui.QScrollArea(self.widget)
        self.thumbComandos.setFrameShape(QtGui.QFrame.Box)
        self.thumbComandos.setFrameShadow(QtGui.QFrame.Plain)
        self.thumbComandos.setLineWidth(1)
        self.thumbComandos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.thumbComandos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thumbComandos.setWidgetResizable(True)
        self.thumbComandos.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.thumbComandos.setObjectName(_fromUtf8("thumbComandos"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 158, 218))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.miniaturas_comandos = QtGui.QVBoxLayout()
        self.miniaturas_comandos.setSpacing(3)
        self.miniaturas_comandos.setObjectName(_fromUtf8("miniaturas_comandos"))
        self.verticalLayout_3.addLayout(self.miniaturas_comandos)
        spacerItem5 = QtGui.QSpacerItem(10, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.thumbComandos.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_5.addWidget(self.thumbComandos)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.aplicarCmd = QtGui.QPushButton(self.widget)
        self.aplicarCmd.setObjectName(_fromUtf8("aplicarCmd"))
        self.horizontalLayout_3.addWidget(self.aplicarCmd)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_8.addWidget(self.widget, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.areaOriginal = QtGui.QFrame(self.centralwidget)
        self.areaOriginal.setFrameShape(QtGui.QFrame.Box)
        self.areaOriginal.setFrameShadow(QtGui.QFrame.Plain)
        self.areaOriginal.setLineWidth(1)
        self.areaOriginal.setObjectName(_fromUtf8("areaOriginal"))
        self.gridLayout = QtGui.QGridLayout(self.areaOriginal)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.label = QtGui.QLabel(self.areaOriginal)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.indicadorOriginal = QtGui.QLabel(self.areaOriginal)
        self.indicadorOriginal.setObjectName(_fromUtf8("indicadorOriginal"))
        self.horizontalLayout_2.addWidget(self.indicadorOriginal)
        spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.nombreOriginal = QtGui.QLabel(self.areaOriginal)
        self.nombreOriginal.setObjectName(_fromUtf8("nombreOriginal"))
        self.horizontalLayout_2.addWidget(self.nombreOriginal)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.aplicar_todas = QtGui.QCheckBox(self.areaOriginal)
        self.aplicar_todas.setObjectName(_fromUtf8("aplicar_todas"))
        self.horizontalLayout_2.addWidget(self.aplicar_todas)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.imgOriginal = QtGui.QScrollArea(self.areaOriginal)
        self.imgOriginal.setFrameShape(QtGui.QFrame.NoFrame)
        self.imgOriginal.setFrameShadow(QtGui.QFrame.Plain)
        self.imgOriginal.setLineWidth(1)
        self.imgOriginal.setWidgetResizable(True)
        self.imgOriginal.setObjectName(_fromUtf8("imgOriginal"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 623, 462))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.img_Original = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.img_Original.setText(_fromUtf8(""))
        self.img_Original.setObjectName(_fromUtf8("img_Original"))
        self.gridLayout_4.addWidget(self.img_Original, 0, 0, 1, 1)
        self.imgOriginal.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.imgOriginal)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 1)
        self.horizontalLayout.addWidget(self.areaOriginal)
        self.gridLayout_8.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuHerramientas = QtGui.QMenu(self.menubar)
        self.menuHerramientas.setObjectName(_fromUtf8("menuHerramientas"))
        self.menuPlugins = QtGui.QMenu(self.menubar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBarPrincipal = QtGui.QToolBar(MainWindow)
        self.toolBarPrincipal.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBarPrincipal.setMovable(False)
        self.toolBarPrincipal.setObjectName(_fromUtf8("toolBarPrincipal"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarPrincipal)
        self.toolBarProcesada = QtGui.QToolBar(MainWindow)
        self.toolBarProcesada.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBarProcesada.setMovable(False)
        self.toolBarProcesada.setObjectName(_fromUtf8("toolBarProcesada"))
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBarProcesada)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(100, 0))
        self.toolBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionEliminar = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/delete_img.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminar.setIcon(icon)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionDeshacer = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/deshacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeshacer.setIcon(icon1)
        self.actionDeshacer.setObjectName(_fromUtf8("actionDeshacer"))
        self.actionRehacer = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/rehacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRehacer.setIcon(icon2)
        self.actionRehacer.setObjectName(_fromUtf8("actionRehacer"))
        self.actionExportar = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/save_one_pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportar.setIcon(icon3)
        self.actionExportar.setObjectName(_fromUtf8("actionExportar"))
        self.actionGuardar = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/save_img.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon4)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionExportarTodas = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/save_all_pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportarTodas.setIcon(icon5)
        self.actionExportarTodas.setObjectName(_fromUtf8("actionExportarTodas"))
        self.actionGuardarTodas = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/save_all_img.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardarTodas.setIcon(icon6)
        self.actionGuardarTodas.setObjectName(_fromUtf8("actionGuardarTodas"))
        self.actionNuevas = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/add_imgs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevas.setIcon(icon7)
        self.actionNuevas.setObjectName(_fromUtf8("actionNuevas"))
        self.actionSalir = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon8)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionAdicionar = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/anex_imgs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdicionar.setIcon(icon9)
        self.actionAdicionar.setObjectName(_fromUtf8("actionAdicionar"))
        self.actionAcerca = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca.setIcon(icon10)
        self.actionAcerca.setObjectName(_fromUtf8("actionAcerca"))
        self.actionMinimizar = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/minimizar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMinimizar.setIcon(icon11)
        self.actionMinimizar.setObjectName(_fromUtf8("actionMinimizar"))
        self.actionAyuda = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAyuda.setIcon(icon12)
        self.actionAyuda.setObjectName(_fromUtf8("actionAyuda"))
        self.actionEliminarTodas = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/delete_img_02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminarTodas.setIcon(icon13)
        self.actionEliminarTodas.setObjectName(_fromUtf8("actionEliminarTodas"))
        self.actionAbrirProyecto = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/open_project_dlx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrirProyecto.setIcon(icon14)
        self.actionAbrirProyecto.setObjectName(_fromUtf8("actionAbrirProyecto"))
        self.actionGuardarProyecto = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/save_project.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardarProyecto.setIcon(icon15)
        self.actionGuardarProyecto.setObjectName(_fromUtf8("actionGuardarProyecto"))
        self.actionLimpiarAreaDeIntercambio = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/clean_swap.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLimpiarAreaDeIntercambio.setIcon(icon16)
        self.actionLimpiarAreaDeIntercambio.setObjectName(_fromUtf8("actionLimpiarAreaDeIntercambio"))
        self.actionGestionar_rea_de_intercambio = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/gest_swap.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGestionar_rea_de_intercambio.setIcon(icon17)
        self.actionGestionar_rea_de_intercambio.setObjectName(_fromUtf8("actionGestionar_rea_de_intercambio"))
        self.menuArchivo.addAction(self.actionNuevas)
        self.menuArchivo.addAction(self.actionAdicionar)
        self.menuArchivo.addAction(self.actionAbrirProyecto)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardarTodas)
        self.menuArchivo.addAction(self.actionExportar)
        self.menuArchivo.addAction(self.actionExportarTodas)
        self.menuArchivo.addAction(self.actionGuardarProyecto)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionMinimizar)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionAcerca)
        self.menuAyuda.addAction(self.actionAyuda)
        self.menuHerramientas.addAction(self.actionLimpiarAreaDeIntercambio)
        self.menuHerramientas.addAction(self.actionGestionar_rea_de_intercambio)
        self.menuHerramientas.addSeparator()
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionEliminar)
        self.menuEditar.addAction(self.actionEliminarTodas)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.toolBarPrincipal.addAction(self.actionNuevas)
        self.toolBarPrincipal.addAction(self.actionAdicionar)
        self.toolBarPrincipal.addAction(self.actionAbrirProyecto)
        self.toolBarProcesada.addAction(self.actionEliminar)
        self.toolBarProcesada.addAction(self.actionEliminarTodas)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionDeshacer)
        self.toolBarProcesada.addAction(self.actionRehacer)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionGuardarProyecto)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionGuardar)
        self.toolBarProcesada.addAction(self.actionGuardarTodas)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionExportar)
        self.toolBarProcesada.addAction(self.actionExportarTodas)
        self.toolBar.addAction(self.actionSalir)
        self.toolBar.addAction(self.actionMinimizar)
        self.toolBar.addAction(self.actionGestionar_rea_de_intercambio)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Imágenes cargadas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Historial de cambios", None, QtGui.QApplication.UnicodeUTF8))
        self.aplicarCmd.setText(QtGui.QApplication.translate("MainWindow", "Aplicar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Imagen: ", None, QtGui.QApplication.UnicodeUTF8))
        self.indicadorOriginal.setText(QtGui.QApplication.translate("MainWindow", "0 de 0", None, QtGui.QApplication.UnicodeUTF8))
        self.nombreOriginal.setText(QtGui.QApplication.translate("MainWindow", "nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.aplicar_todas.setText(QtGui.QApplication.translate("MainWindow", "Aplicar a todas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHerramientas.setTitle(QtGui.QApplication.translate("MainWindow", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlugins.setTitle(QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditar.setTitle(QtGui.QApplication.translate("MainWindow", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarPrincipal.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarProcesada.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminar.setText(QtGui.QApplication.translate("MainWindow", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeshacer.setText(QtGui.QApplication.translate("MainWindow", "Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRehacer.setText(QtGui.QApplication.translate("MainWindow", "Rehacer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportar.setText(QtGui.QApplication.translate("MainWindow", "Exportar actual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportar.setToolTip(QtGui.QApplication.translate("MainWindow", "Exportar actual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("MainWindow", "Guardar actual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setToolTip(QtGui.QApplication.translate("MainWindow", "Guardar actual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportarTodas.setText(QtGui.QApplication.translate("MainWindow", "Exportar todas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportarTodas.setToolTip(QtGui.QApplication.translate("MainWindow", "Exportar todas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardarTodas.setText(QtGui.QApplication.translate("MainWindow", "Guardar todas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardarTodas.setToolTip(QtGui.QApplication.translate("MainWindow", "Guardar todas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevas.setText(QtGui.QApplication.translate("MainWindow", "Nuevas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdicionar.setText(QtGui.QApplication.translate("MainWindow", "Adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca.setText(QtGui.QApplication.translate("MainWindow", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca.setToolTip(QtGui.QApplication.translate("MainWindow", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimizar.setText(QtGui.QApplication.translate("MainWindow", "Minimizar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAyuda.setText(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminarTodas.setText(QtGui.QApplication.translate("MainWindow", "Eliminar todas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminarTodas.setToolTip(QtGui.QApplication.translate("MainWindow", "Eliminar todas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrirProyecto.setText(QtGui.QApplication.translate("MainWindow", "Abrir proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrirProyecto.setToolTip(QtGui.QApplication.translate("MainWindow", "Abrir proyecto .dlx", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardarProyecto.setText(QtGui.QApplication.translate("MainWindow", "Guardar proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardarProyecto.setToolTip(QtGui.QApplication.translate("MainWindow", "Guardar proyecto .dlx", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLimpiarAreaDeIntercambio.setText(QtGui.QApplication.translate("MainWindow", "Limpiar área de intercambio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLimpiarAreaDeIntercambio.setToolTip(QtGui.QApplication.translate("MainWindow", "Limpiar área de intercambio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGestionar_rea_de_intercambio.setText(QtGui.QApplication.translate("MainWindow", "Gestionar área de intercambio", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGestionar_rea_de_intercambio.setToolTip(QtGui.QApplication.translate("MainWindow", "Gestionar área de intercambio", None, QtGui.QApplication.UnicodeUTF8))

import recursos_rc
