# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created: Fri Oct 11 12:10:10 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

# from PyQt6 import QtCore, QtGui
from PyQt5 import QtGui, QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(5)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.areaOriginal = QtWidgets.QFrame(self.splitter)
        self.areaOriginal.setFrameShape(QtWidgets.QFrame.Box)
        self.areaOriginal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.areaOriginal.setLineWidth(1)
        self.areaOriginal.setObjectName(_fromUtf8("areaOriginal"))
        self.gridLayout = QtWidgets.QGridLayout(self.areaOriginal)
        self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.areaOriginal)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.indicadorOriginal = QtWidgets.QLabel(self.areaOriginal)
        self.indicadorOriginal.setObjectName(_fromUtf8("indicadorOriginal"))
        self.horizontalLayout_2.addWidget(self.indicadorOriginal)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.nombreOriginal = QtWidgets.QLabel(self.areaOriginal)
        self.nombreOriginal.setObjectName(_fromUtf8("nombreOriginal"))
        self.horizontalLayout_2.addWidget(self.nombreOriginal)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.imgOriginal = QtWidgets.QScrollArea(self.areaOriginal)
        self.imgOriginal.setMinimumSize(QtCore.QSize(200, 0))
        self.imgOriginal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgOriginal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgOriginal.setLineWidth(1)
        self.imgOriginal.setWidgetResizable(True)
        self.imgOriginal.setObjectName(_fromUtf8("imgOriginal"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 291, 343))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.img_Original = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_Original.setText(_fromUtf8(""))
        self.img_Original.setObjectName(_fromUtf8("img_Original"))
        self.gridLayout_4.addWidget(self.img_Original, 0, 0, 1, 1)
        self.imgOriginal.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.imgOriginal)
        self.thumbOriginal = QtWidgets.QScrollArea(self.areaOriginal)
        self.thumbOriginal.setMinimumSize(QtCore.QSize(200, 80))
        self.thumbOriginal.setMaximumSize(QtCore.QSize(16777215, 80))
        self.thumbOriginal.setFrameShape(QtWidgets.QFrame.Box)
        self.thumbOriginal.setFrameShadow(QtWidgets.QFrame.Plain)
        self.thumbOriginal.setLineWidth(1)
        self.thumbOriginal.setWidgetResizable(True)
        self.thumbOriginal.setObjectName(_fromUtf8("thumbOriginal"))
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 289, 78))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.miniaturas_originales = QtWidgets.QHBoxLayout()
        self.miniaturas_originales.setSpacing(5)
        self.miniaturas_originales.setObjectName(_fromUtf8("miniaturas_originales"))
        self.gridLayout_6.addLayout(self.miniaturas_originales, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 1, 1, 1)
        self.thumbOriginal.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.thumbOriginal)
        self.gridLayout.addLayout(self.verticalLayout, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.areaOriginal)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.areaProcesada = QtWidgets.QFrame(self.splitter)
        self.areaProcesada.setFrameShape(QtWidgets.QFrame.Box)
        self.areaProcesada.setFrameShadow(QtWidgets.QFrame.Plain)
        self.areaProcesada.setLineWidth(1)
        self.areaProcesada.setObjectName(_fromUtf8("areaProcesada"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.areaProcesada)
        self.gridLayout_2.setContentsMargins(0,0,0,0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_4 = QtWidgets.QLabel(self.areaProcesada)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.imgProcesada = QtWidgets.QScrollArea(self.areaProcesada)
        self.imgProcesada.setMinimumSize(QtCore.QSize(400, 0))
        self.imgProcesada.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgProcesada.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgProcesada.setWidgetResizable(True)
        self.imgProcesada.setObjectName(_fromUtf8("imgProcesada"))
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 479, 335))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.img_Procesada = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.img_Procesada.setText(_fromUtf8(""))
        self.img_Procesada.setPixmap(QtGui.QPixmap(_fromUtf8("../recursos/Archivo11.JPG")))
        self.img_Procesada.setObjectName(_fromUtf8("img_Procesada"))
        self.gridLayout_5.addWidget(self.img_Procesada, 1, 0, 1, 1)
        self.imgProcesada.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.imgProcesada)
        self.thumbProcesada = QtWidgets.QScrollArea(self.areaProcesada)
        self.thumbProcesada.setMinimumSize(QtCore.QSize(0, 80))
        self.thumbProcesada.setMaximumSize(QtCore.QSize(16777215, 80))
        self.thumbProcesada.setFrameShape(QtWidgets.QFrame.Box)
        self.thumbProcesada.setFrameShadow(QtWidgets.QFrame.Plain)
        self.thumbProcesada.setLineWidth(1)
        self.thumbProcesada.setWidgetResizable(True)
        self.thumbProcesada.setObjectName(_fromUtf8("thumbProcesada"))
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 477, 78))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.miniaturas_procesadas = QtWidgets.QHBoxLayout()
        self.miniaturas_procesadas.setSpacing(5)
        self.miniaturas_procesadas.setObjectName(_fromUtf8("miniaturas_procesadas"))
        self.gridLayout_7.addLayout(self.miniaturas_procesadas, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem8, 0, 1, 1, 1)
        self.thumbProcesada.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.addWidget(self.thumbProcesada)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_2 = QtWidgets.QLabel(self.areaProcesada)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.indicadorProcesada = QtWidgets.QLabel(self.areaProcesada)
        self.indicadorProcesada.setObjectName(_fromUtf8("indicadorProcesada"))
        self.horizontalLayout_3.addWidget(self.indicadorProcesada)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.nombreProcesada = QtWidgets.QLabel(self.areaProcesada)
        self.nombreProcesada.setObjectName(_fromUtf8("nombreProcesada"))
        self.horizontalLayout_3.addWidget(self.nombreProcesada)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.aplicar_todas = QtWidgets.QCheckBox(self.areaProcesada)
        self.aplicar_todas.setObjectName(_fromUtf8("aplicar_todas"))
        self.horizontalLayout_3.addWidget(self.aplicar_todas)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName(_fromUtf8("menuHerramientas"))
        self.menuPlugins = QtWidgets.QMenu(self.menubar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBarPrincipal = QtWidgets.QToolBar(MainWindow)
        self.toolBarPrincipal.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBarPrincipal.setMovable(False)
        self.toolBarPrincipal.setObjectName(_fromUtf8("toolBarPrincipal"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarPrincipal)
        self.toolBarOriginal = QtWidgets.QToolBar(MainWindow)
        self.toolBarOriginal.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBarOriginal.setMovable(False)
        self.toolBarOriginal.setObjectName(_fromUtf8("toolBarOriginal"))
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBarOriginal)
        self.toolBarProcesada = QtWidgets.QToolBar(MainWindow)
        self.toolBarProcesada.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBarProcesada.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBarProcesada.setMovable(False)
        self.toolBarProcesada.setObjectName(_fromUtf8("toolBarProcesada"))
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBarProcesada)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(100, 0))
        self.toolBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionEliminar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/delete_image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminar.setIcon(icon)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionDeshacer = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/deshacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeshacer.setIcon(icon1)
        self.actionDeshacer.setObjectName(_fromUtf8("actionDeshacer"))
        self.actionRehacer = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/rehacer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRehacer.setIcon(icon2)
        self.actionRehacer.setObjectName(_fromUtf8("actionRehacer"))
        self.actionExportar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/exportar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportar.setIcon(icon3)
        self.actionExportar.setObjectName(_fromUtf8("actionExportar"))
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/guardar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon4)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionExportarTodas = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/exportar_todas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportarTodas.setIcon(icon5)
        self.actionExportarTodas.setObjectName(_fromUtf8("actionExportarTodas"))
        self.actionGuardarTodas = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/guardar_todas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardarTodas.setIcon(icon6)
        self.actionGuardarTodas.setObjectName(_fromUtf8("actionGuardarTodas"))
        self.actionListaComandos = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/lista_cmds.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionListaComandos.setIcon(icon7)
        self.actionListaComandos.setObjectName(_fromUtf8("actionListaComandos"))
        self.actionNuevas = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/nuevas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuevas.setIcon(icon8)
        self.actionNuevas.setObjectName(_fromUtf8("actionNuevas"))
        self.actionSalir = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/apagar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon9)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionSeleccionar_actual = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/seleccionar_actual.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSeleccionar_actual.setIcon(icon10)
        self.actionSeleccionar_actual.setObjectName(_fromUtf8("actionSeleccionar_actual"))
        self.actionSeleccionar_todas = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/seleccionar_todas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSeleccionar_todas.setIcon(icon11)
        self.actionSeleccionar_todas.setObjectName(_fromUtf8("actionSeleccionar_todas"))
        self.actionAdicionar = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/adicionar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdicionar.setIcon(icon12)
        self.actionAdicionar.setObjectName(_fromUtf8("actionAdicionar"))
        self.actionAcerca = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/docluxlogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca.setIcon(icon13)
        self.actionAcerca.setObjectName(_fromUtf8("actionAcerca"))
        self.actionMinimizar = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/recursos/imagenes/minimizar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMinimizar.setIcon(icon14)
        self.actionMinimizar.setObjectName(_fromUtf8("actionMinimizar"))
        self.menuArchivo.addAction(self.actionNuevas)
        self.menuArchivo.addAction(self.actionAdicionar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardarTodas)
        self.menuArchivo.addAction(self.actionExportar)
        self.menuArchivo.addAction(self.actionExportarTodas)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionMinimizar)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionAcerca)
        self.menuHerramientas.addAction(self.actionSeleccionar_actual)
        self.menuHerramientas.addAction(self.actionSeleccionar_todas)
        self.menuHerramientas.addSeparator()
        self.menuHerramientas.addAction(self.actionListaComandos)
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionEliminar)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.toolBarPrincipal.addAction(self.actionNuevas)
        self.toolBarPrincipal.addAction(self.actionAdicionar)
        self.toolBarOriginal.addAction(self.actionEliminar)
        self.toolBarOriginal.addSeparator()
        self.toolBarOriginal.addAction(self.actionSeleccionar_actual)
        self.toolBarOriginal.addAction(self.actionSeleccionar_todas)
        self.toolBarProcesada.addAction(self.actionListaComandos)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionExportarTodas)
        self.toolBarProcesada.addAction(self.actionExportar)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionGuardarTodas)
        self.toolBarProcesada.addAction(self.actionGuardar)
        self.toolBarProcesada.addSeparator()
        self.toolBarProcesada.addAction(self.actionRehacer)
        self.toolBarProcesada.addAction(self.actionDeshacer)
        self.toolBar.addAction(self.actionSalir)
        self.toolBar.addAction(self.actionMinimizar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Imagen: ", None))
        self.indicadorOriginal.setText(QtWidgets.QApplication.translate("MainWindow", "0 de 0", None))
        self.nombreOriginal.setText(QtWidgets.QApplication.translate("MainWindow", "nombre", None))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Imagen Original", None))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Imagen Procesada", None))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Imagen: ", None))
        self.indicadorProcesada.setText(QtWidgets.QApplication.translate("MainWindow", "0 de 0", None))
        self.nombreProcesada.setText(QtWidgets.QApplication.translate("MainWindow", "nombre", None))
        self.aplicar_todas.setText(QtWidgets.QApplication.translate("MainWindow", "Aplicar a todas", None))
        self.menuArchivo.setTitle(QtWidgets.QApplication.translate("MainWindow", "Archivo", None))
        self.menuAyuda.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ayuda", None))
        self.menuHerramientas.setTitle(QtWidgets.QApplication.translate("MainWindow", "Herramientas", None))
        self.menuPlugins.setTitle(QtWidgets.QApplication.translate("MainWindow", "Plugins", None))
        self.menuEditar.setTitle(QtWidgets.QApplication.translate("MainWindow", "Editar", None))
        self.toolBarPrincipal.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None))
        self.toolBarOriginal.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar_2", None))
        self.toolBarProcesada.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar_3", None))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None))
        self.actionEliminar.setText(QtWidgets.QApplication.translate("MainWindow", "Eliminar", None))
        self.actionDeshacer.setText(QtWidgets.QApplication.translate("MainWindow", "Deshacer", None))
        self.actionRehacer.setText(QtWidgets.QApplication.translate("MainWindow", "Rehacer", None))
        self.actionExportar.setText(QtWidgets.QApplication.translate("MainWindow", "Exportar actual", None))
        self.actionExportar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Exportar actual", None))
        self.actionGuardar.setText(QtWidgets.QApplication.translate("MainWindow", "Guardar actual", None))
        self.actionGuardar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Guardar actual", None))
        self.actionExportarTodas.setText(QtWidgets.QApplication.translate("MainWindow", "Exportar todas", None))
        self.actionExportarTodas.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Exportar todas", None))
        self.actionGuardarTodas.setText(QtWidgets.QApplication.translate("MainWindow", "Guardar todas", None))
        self.actionGuardarTodas.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Guardar todas", None))
        self.actionListaComandos.setText(QtWidgets.QApplication.translate("MainWindow", "Lista de comandos", None))
        self.actionListaComandos.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Lista de comandos", None))
        self.actionNuevas.setText(QtWidgets.QApplication.translate("MainWindow", "Nuevas", None))
        self.actionSalir.setText(QtWidgets.QApplication.translate("MainWindow", "Salir", None))
        self.actionSeleccionar_actual.setText(QtWidgets.QApplication.translate("MainWindow", "Seleccionar actual", None))
        self.actionSeleccionar_todas.setText(QtWidgets.QApplication.translate("MainWindow", "Seleccionar todas", None))
        self.actionAdicionar.setText(QtWidgets.QApplication.translate("MainWindow", "Adicionar", None))
        self.actionAcerca.setText(QtWidgets.QApplication.translate("MainWindow", "Acerca", None))
        self.actionAcerca.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Acerca de", None))
        self.actionMinimizar.setText(QtWidgets.QApplication.translate("MainWindow", "Minimizar", None))

from .recursos_rc import *
